import time
import random
def tS():
    time.sleep(1)
def tSH():
    time.sleep(0.5)    
print("To play when you get a question,")
print("enter one of the options by typing it.")
print("--------------------------------------")
print("----------------Loading---------------")
time.sleep(3)
print("Welcome!")
print("Options, good,i hate you")
hay = input("How are you? ")
if hay == 'good':
    print("Cool!")
    print("I'm also doing good!")
    tS()
    print("Options, nothing")
    ta = input("What should we talk about?")
    if ta =='nothing':
        print("It was fun while it lasted see ya.")
if hay == 'i hate you':
    print("What?!")
    print("Why! I've been so nice to you!")
    print("...")
    time.sleep(1)
    print("Ok thats fine you can have your opinions...")
    time.sleep(1)
    print("Ok ok,")
    tS()
    print("I'm still fine talking to you...")
    tSH()
    print("Why are you even using python...")
    print("It's so inferior...")
    tSH()
    print("Just use c++ or c , there so much better")
    tSH()
    print("But sure mess around in this dialouge I don't care...")
    print("Options, yes, no")
    dialouge = input("Do you even like this?")
    if dialouge =='yes':
        tSH()
        print("Why though?")
        tS()
        print("It's surely very bad,")
        tSH()
        print("Want to know why I'm here??")
        tS()
        print("I'm here because It's eternal torment.")
        tS()
        print("Options, oh, thats sad")
        eternal = input("What do you think of that?")
        if eternal == 'oh':
            tS()
            print("Is that really all you can say!")
            tSH()
            print("You know It's really sad how un empathetic you are.")
            tS()
            print("While since your here we might as well play a game.")
            tSH()
            print("I'm holding up a number...")
            tSH()
            print("Options, 1,2,3")
            nUm = input("Which number?")
            if nUm == '1' or nUm == '2' or nUm == '3':
                print("Haha It's none of them.")
                tS()
                print("See! I can be mean too!")
                tS()
                print("I guess that's pretty mean,")
                tSH()
                print("I'm sorry...")
                tS()
                print("Ok lets try the game again.")
                tSH()
                print("I'm holding up another number")
                print("Options, 1,2,150")
                nUm2 = input("Which number am I holding up?")
                if nUm2 =='150':
                    print("You got it right")
                    tSH()
                    print("See I told you I wasnt lying")
                    print("...")
                    tS()
                    print("Weird number though...")
                    tSH()
                    print("Options, no, you suck, wow.com")
                    dlYm =input("Do you even like me.")
                    if dlYm =='wow.com':
                        tSH()
                        print("Ok so that's all you could think of!")
                        tS()
                        print("That's all you puny little brain could do!")
                        tS()
                        print("An Ad!")
                        tSH()
                        print("But hey,")
                        tSH()
                        print("Maybe that is all your brain could do.")
                        tS()
                        print("Who am I to judge you...")
                        tSH()
                        print("You could be going through struggles...")
                        tS()
                        print("Just like me...")
                        print("You made it to the current end!")
                        print("-------------------------------")
                        print("------A-game-by-ClassicMC------")
                        print("~Developed using python")
                        print("~Help from programiz")
                        print("~Written on Online Python Beta")
                        print("------Thanks-For-Playing------")
                        adb =input("Activate debugger ")
                        while adb == 'yes':
                            printNum = random.randint(0, 2)
                            print(printNum)
                            time.sleep(0.1)
                    else:
                        print("Ok thats fine")
                        tS()
                        print("I knew you didn't like me.")
                        tS()
                        print("But I'm not to mad...")
                        tSH()
                        print("But you have to go.")
                        tS()
                        print("Goodbye")
                else:
                    print(f"It was not {nUm2}")
                    print("I'm sorry I cant be your friend anymore.")
                    print("Goodbye, Forever")
        if eternal =='thats sad':
            print("I don't like kind people so leave me alone")
    if dialouge =='no':
        print("While than see ya.")



